"""add agent_name to audit_logs

Revision ID: 49704d1de009
Revises: c5874b84ca69
Create Date: 2026-03-16 17:05:11.236069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49704d1de009'
down_revision: Union[str, Sequence[str], None] = 'c5874b84ca69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('agent_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_audit_logs_agent_name'), 'audit_logs', ['agent_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_agent_name'), table_name='audit_logs')
    op.drop_column('audit_logs', 'agent_name')
    # ### end Alembic commands ###
