"""init audit_logs table

Revision ID: c5874b84ca69
Revises: c670e0ef4d5a
Create Date: 2026-03-16 00:15:24.705458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5874b84ca69'
down_revision: Union[str, Sequence[str], None] = 'c670e0ef4d5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'request_ip',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('audit_logs', 'task_category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('audit_logs', 'budget_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('audit_logs', 'best_model_id',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_comment='系统推荐的最优模型')
    op.alter_column('audit_logs', 'routing_cascade',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_comment='完整的备选梯队完整快照')
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('audit_logs', 'routing_cascade',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_comment='完整的备选梯队完整快照')
    op.alter_column('audit_logs', 'best_model_id',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_comment='系统推荐的最优模型')
    op.alter_column('audit_logs', 'budget_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('audit_logs', 'task_category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('audit_logs', 'request_ip',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
