"""init audit_logs table

Revision ID: c670e0ef4d5a
Revises: 
Create Date: 2026-03-16 00:08:47.235166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c670e0ef4d5a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_ip', sa.String(), nullable=True),
    sa.Column('task_category', sa.String(), nullable=True),
    sa.Column('budget_usd', sa.Float(), nullable=True),
    sa.Column('best_model_id', sa.String(), nullable=True, comment='系统推荐的最优模型'),
    sa.Column('routing_cascade', sa.JSON(), nullable=True, comment='完整的备选梯队完整快照'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_ip'), 'audit_logs', ['request_ip'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_request_ip'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
